name: Test job
on:
  push:
    branches: [ main ]

jobs:
  Server:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/server-tests
  Client:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/client-tests
  Backoffice:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/backoffice-tests
  Backoffice_E2E:
    runs-on: ubuntu-22.04 # "latest" fails on Playwright deps install
    needs: [Client, Server, Backoffice]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: schronisko
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/backoffice-e2e
  Client_E2E:
    runs-on: ubuntu-22.04 # "latest" fails on Playwright deps install
    needs: [Client, Server, Backoffice]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: schronisko
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/client-e2e
